// common
export const REQUEST_POSTS = 'REQUEST_POSTS';
export const RECEIVE_POSTS = 'RECEIVE_POSTS';
export const SET_MASK = 'SET_MASK';
export const SET_ROUTER = 'SET_ROUTER';
// BankSelect
export const SET_BANK = 'SET_BANK';
export const SET_BANK_ERROR = 'SET_BANK_ERROR';
// DepositWay
export const SET_DEPOSIT_WAY = 'SET_DEPOSIT_WAY';
export const SET_PROVINCE = 'SET_PROVINCE';
export const SET_BRANCH = 'SET_BRANCH';
export const SET_COUNTY = 'SET_COUNTY';
export const SET_ACCELERATED_ACCOUNT_SHOW = 'SET_ACCELERATED_ACCOUNT_SHOW';

// memberData
export const REQUEST_MEMBER_DATA_POSTS = 'REQUEST_MEMBER_DATA_POSTS';
export const RECEIVE_MEMBER_DATA_POSTS = 'RECEIVE_MEMBER_DATA_POSTS';

// moneySwitch
export const REQUEST_MONEY_SWITCH_POSTS = 'REQUEST_MONEY_SWITCH_POSTS';
export const RECEIVE_MONEY_SWITCH_POSTS = 'RECEIVE_MONEY_SWITCH_POSTS';
export const ADD_COUNT = 'ADD_COUNT';

// DepositAccount
export const SET_DEPOSIT_ACCOUNTNAME = 'SET_DEPOSIT_ACCOUNTNAME';
export const SET_DEPOSIT_ACCOUNT = 'SET_DEPOSIT_ACCOUNT';
export const SET_DEPOSIT_ACCOUNT_ERROR = 'SET_DEPOSIT_ACCOUNT_ERROR';
export const SET_DEPOSIT_ACCOUNT_SYMBOL_ERROR = 'SET_DEPOSIT_ACCOUNT_SYMBOL_ERROR';

// DepositAmount
export const SET_DEPOSIT_AMOUNT = 'SET_DEPOSIT_AMOUNT';
export const SET_PREFERENTIAL = 'SET_PREFERENTIAL';
export const SET_EXPLANATION_SHOW = 'SET_EXPLANATION_SHOW';


// StepForm
export const SET_FORM_SHOW = 'SET_FORM_SHOW';
export const SET_PREFERENTIAL_LABEL_SHOW = 'SET_PREFERENTIAL_LABEL_SHOW';
export const DEPOSIT_ACCOUNT_LABEL_SHOW = 'DEPOSIT_ACCOUNT_LABEL_SHOW';
export const SET_STEP1_HIDE = 'SET_STEP1_HIDE';
export const SET_STEP2_SHOW = 'SET_STEP2_SHOW';
