// common
export const REQUEST_POSTS = 'REQUEST_POSTS';
export const RECEIVE_POSTS = 'RECEIVE_POSTS';
export const SET_MASK = 'SET_MASK';

// memberData
export const REQUEST_MEMBER_DATA_POSTS = 'REQUEST_MEMBER_DATA_POSTS';
export const RECEIVE_MEMBER_DATA_POSTS = 'RECEIVE_MEMBER_DATA_POSTS';

// moneySwitch
export const REQUEST_MONEY_SWITCH_POSTS = 'REQUEST_MONEY_SWITCH_POSTS';
export const RECEIVE_MONEY_SWITCH_POSTS = 'RECEIVE_MONEY_SWITCH_POSTS';
export const ADD_COUNT = 'ADD_COUNT';
